[build]
entrypoints = ["src/index.ts"]
outdir = "dist"
target = "bun"
minify = true
sourcemap = "external"

[build.define]
process.env.NODE_ENV = "production"

[install]
# Ensure all dependencies are installed
exact = false 