name: General Issue
description: General questions, discussions, or other issues not covered by other templates
title: "[Question]: "
labels: ["question", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Use this template for questions, discussions, or issues that don't fit the bug report or feature request categories.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - "Question / Help needed"
        - "Documentation issue"
        - "Installation/setup problem"
        - "Performance concern"
        - "Security question"
        - "Integration question"
        - "Discussion/RFC"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your question, concern, or issue in detail
      placeholder: |
        What would you like to know or discuss?
        What problem are you trying to solve?
        What documentation or clarification do you need?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and Background
      description: Provide any relevant context that might help others understand your question
      placeholder: |
        What are you trying to achieve?
        What have you already tried?
        Any relevant environment details?
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or Code
      description: If applicable, provide examples or code snippets
      render: shell
      placeholder: |
        # Commands you've tried:
        lpop --help
        
        # Expected behavior:
        Should show help text
        
        # What you're seeing:
        Command not recognized
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might be helpful
      placeholder: Links, screenshots, logs, or any other relevant information...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar topics
          required: true
        - label: I have provided enough context for others to understand my question/issue
          required: true