name: Tests

on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies for keyring (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-dev

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Run tests with coverage
        run: bun run test:coverage
        if: matrix.os == 'ubuntu-latest' # Only run coverage on one OS to save time

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: coverage-reports
          path: coverage/
          retention-days: 30
